name: Run Playwright Tests

on:
  push:
    branches:
      - main
      - ci
  repository_dispatch:
    types: [app-updated]

jobs:
    run-playwright-tests:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/playwright:v1.50.0-noble
        options: --init --ipc=host --cap-add=SYS_ADMIN --user 1001
        env:
          BASE_URL: "http://banquet-app:3000"
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
      services:
        banquet-app:
          image: ${{ vars.DOCKERHUB_USERNAME }}/banquet:latest
          ports:
            - 3000:3000
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            ALLOW_DB_RESET: ${{ secrets.ALLOW_DB_RESET }}
            TEST_SECRET: ${{ secrets.TEST_SECRET }}
      steps:
        - name: Wait for app
          run: npx wait-on http://banquet-app:3000

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v7
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci

        - name: Install Playwright browsers
          run: npx playwright install --with-deps

        - name: Run Playwright tests
          run: |
            npx playwright test --project=chromium
            npx playwright test --project=firefox
            npx playwright test --project=webkit

        - name: Upload Playwright reports
          uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: execution-reports
            path: execution-reports/
            retention-days: 90

        - name: Collect Docker logs
          if: ${{ failure() }}
          run: docker logs banquet-app > docker.log

        - name: Upload Docker logs
          uses: actions/upload-artifact@v4
          if: ${{ failure() }}
          with:
            name: docker-logs
            path: docker.log


        - name: Stop the application
          if: ${{ always() }}
          run: docker container stop banquet-app